export const posts =
[
    {
      "id": 1,
      "title": "Data exported by Team Cloud organization",
      "fullTitle" : "Data exported by Team Cloud organization administrators contained private files",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",      
      "summary": "An internal investigation recently uncovered a vulnerability (identified as CVE-2022-21706) in Zulip’s invitation links.",
      "image": "/images/posts_img/post1.png",
      "category": "Security",
      "date": "July 1, 2023"
    },
    {
      "id": 2,
      "title": "Swap long video calls and emails for asynchronous video",
      "fullTitle" : "Swap long video calls and emails for asynchronous video contained private files",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",      
      "summary": "Meetings are essential for communication and team building, but they're often unproductive. Asynchronous video to the rescue.",
      "image": "/images/posts_img/post2.png",
      "category": "Communication",
      "date": "June 21, 2023"
    },
    {
      "id": 3,
      "title": "Flexibility reigns: six key takeaways from Frontiers 2023",
      "fullTitle" : "Flexibility reigns: six key takeaways from Frontiers 2023",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",      
      "summary": "The future of work is having a digital HQ that works for you.",
      "image": "/images/posts_img/post3.png",
      "category": "Business",
      "date": "June 10, 2023"
    },
    {
      "id": 4,
      "title": "Team plus Sales Cloud: Your sales team’s new digital HQ",
      "fullTitle" : "Team plus Sales Cloud: Your sales team’s new digital HQ",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",      
      "summary": "Why everyone on your sales team will benefit from our app's killer features.",
      "image": "/images/posts_img/post4.png",
      "category": "Sales",
      "date": "May 12, 2023"
    },
    {
      "id": 5,
      "title": "What is digital culture?",
      "fullTitle" : "What is digital culture?",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",   
      "summary": "The teams best prepared for change use modern digital communication tools, feel comfortable learning new ones and continually adapt how they work.",
      "image": "/images/posts_img/post5.png",
      "category": "Culture",
      "date": "May 22, 2023"
    },
    {
      "id": 6,
      "title": "Steve Dotto’s top 10 tips for overcoming workplace hiccups",
      "fullTitle" : "Steve Dotto’s top 10 tips for overcoming workplace hiccups",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",   
      "summary": "The executive producer of Dotto Tech shares his favorite slick strategies for conquering common challenges in the digital-first workplace.",
      "image": "/images/posts_img/post6.png",
      "category": "Productivity",
      "date": "April 4, 2023"
    },
    {
      "id": 7,
      "title": "What’s new in Team: iPad updates, split-screen view and more",
      "fullTitle" : "What’s new in Team: iPad updates, split-screen view and more",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",   
      "summary": "An internal investigation recently uncovered a vulnerability (identified as CVE-2022-21706) in Zulip’s invitation links.",
      "image": "/images/posts_img/post7.png",
      "category": "Technology",
      "date": "March 18, 2023"
    },
    {
      "id": 8,
      "title": "Drive more efficiency and cost savings with these updates to Workflow Builder",
      "fullTitle" : "Drive more efficiency and cost savings with these updates to Workflow Builder",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",   
      "summary": "New and upcoming automation features help your team do more with less.",
      "image": "/images/posts_img/post8.png",
      "category": "Efficiency",
      "date": "February 18, 2023"
    },
    {
      "id": 9,
      "title": "7 tips to onboard sales reps with ease",
      "fullTitle" : "7 tips to onboard sales reps with ease",
      "fullSummary1" : "Administrators of Team Cloud organizations can export public data from their organization via the organization settings menu. The exports include all the data that appears in public streams, and can be used to migrate from Team Cloud to self-hosting Team. Note that exporting private data is a separate process that requires contacting Team Support.",
      "fullSummary2" : "Due to a bug in the public export code, exports of public data contained all uploaded files, even those from private messages and private streams. This may have allowed organization owners or administrators to extract uploaded files that they were not otherwise allowed to access. The content of non-public messages was never included in public exports.",
      "fullSummary3" : "This bug has existed since the public export feature was implemented in August 2019. We have deleted all existing Team Cloud exports from our servers, and will be making changes to auto-expire all exports after 7 days in the future. This bug was fixed for self-hosted users in the Team Server 5.4 release.",
      "fullSummary4" : "We have notified by email all administrators and users in non-deactivated Team Cloud organizations who may have been impacted by this bug. As many organizations have never exported their data, most Team Cloud users were not affected.",
      "fullSummary5" : "We would like to thank Antoine Benoist for bringing this issue to our attention.",   
      "summary": "The executive producer of Dotto Tech shares his favorite slick strategies for conquering common challenges in the digital-first workplace.",
      "image": "/images/posts_img/post9.png",
      "category": "Human Resources",
      "date": "January 7, 2023"
    }
]